const itemsDE = {
    weapons: [
        ["Ahavarion, Stab von Lycander", "Es besteht eine Chance, dass beim Töten eines Dämons ein zufälliger Schreineffekt auf Euch gewirkt wird"],
        ["Aschebeil", "Chance von 50%, einen Feuerball zu wirken, wenn Ihr angreift"],
        ["Blankbogen von K'mar", "'Sperrfeuer' erhält den Effekt der Rune 'Wehender Schatten'"],
        ["Buriza-Do Kyanon", "Eure Geschosse durchschlagen ihre Ziele zusätzlich 2-mal"],
        ["Die Faust von Az'Turrasq", "Erhöht den Schaden der Todesexplosion von 'Explodierende Hand' um 300% "],
        ["Eun-jang-do", "Gegner, die über weniger als 20% ihres Lebens verfügen, werden durch Eure Angriffe für 3 Sek. eingefroren"],
        ["Goldgeißel", "'Niederstrecken' springt jetzt auf 3 weitere Gegner über"],
        ["In-geom", "Die Abklingzeiten Eurer Fertigkeiten werden jedes Mal 15 Sek. lang um 10 Sek. reduziert, wenn Ihr eine Gruppe von Elitegegnern tötet"],
        ["Kosmischer Strang", "'Teleportation' erhält den Effekt der Rune 'Wurmloch'"],
        ["Mauer der Menschheit", "Chance von 30%, Euch mit einem Knochenschild zu umgeben, wenn Ihr getroffen werdet"],
        ["Orpheus' Wink", "Reduziert die Abklingzeit von 'Zeit verlangsamen' um 40 %"],
        ["Piro Marella", "Reduziert die Zornkosten von 'Schildstoß' um 50%"],
        ["Rhen'hos Schinder", "Eure Kröten verfolgen Gegner jetzt und können zweimal explodieren"],
        ["Unbarmherzigkeit", "'Hammer der Urahnen' hat eine Chance von 30%, für 20 Sek. einen Urahnen zu beschwören"],
        ["Vo'Toyias' Dornschild", "Gegner, die von 'Provokation' betroffen sind, erleiden doppelten Schaden durch Dornen"],
        ["Zerfetzer", "Chance von 50%, den Boden unter den Füßen Eurer Gegner aufbrechen zu lassen, wenn Ihr angreift"],
        ["Ablenkender Frost", "Wenn Ihr einen Angriff blockt, besteht die Chance, den Angreifer 0,5-1,5 Sek. lang einzufrieren"],
        ["Akarats Erwachen", "Jedes erfolgreiche Blocken eines Angriffs hat eine Chance von 25%, jegliche Abklingzeiten um 1 Sek. zu reduzieren"],
        ["Akkurate Bolzen", "Der Kugelblitz von 'Elementarpfeil' bewegt sich mit einer Geschwindigkeit von 40%"],
        ["Anessazi-Stilett", "Zombiehunde betäuben Gegner um sie herum für 1,5 Sek., wenn sie beschworen werden"],
        ["Arthefs Lebensfunke", "Ihr werdet um 3-4% Eures verlorenen Lebens geheilt, wenn Ihr einen untoten Gegner tötet"],
        ["Ausbruch des Zorns", "Das Töten von Gegnern und Zerstören von Objekten hat eine Chance, Euch 20% Eurer maximalen Primärressource zu gewähren"],
        ["Blauzorn", "Untote und dämonische Gegner innerhalb von 25 Metern erleiden jede Sekunde 650% Waffenschaden als Heiligschaden und werden manchmal in die Luft geschleudert."],
        ["Blutsbruder", "Gewährt eine Chance von 20%, dass Angriffe geblockt werden. Geblockte Angriffe verursachen 30% weniger Schaden. Nach dem Blocken eines Angriffs verursacht Euer nächster Angriff 30% mehr Schaden."],
        ["Cams Erwiderung", "'Himmlische Vollstreckung' kann innerhalb von 4 Sek. wieder eingesetzt werden, bevor die Abklingzeit ausgelöst wird"],
        ["Chanons Balläster", "Eure Stachelfallen locken Gegner an. Gegner können einmal alle 16 Sek. angelockt werden"],
        ["Danettas Rache", "'Salto' erhält den Effekt der Rune 'Geschüttelt, nicht gerührt'"],
        ["Danettas Trotz", "Ihr hinterlasst beim Einsatz von 'Salto' eine Kopie von Euch"],
        ["Das Gesetz des Arreat", "'Waffenwurf' erzeugt mit zunehmender Entfernung zum getroffenen Gegner zusätzlich bis zu 20 mehr Wut. Der Maximalwert wird ab 20 Meter erreicht."],
        ["Der Dolchpfeil", "Eure Giftpfeile und die Giftpfeile Eurer Fetische durchschlagen ihre Ziele"],
        ["Der Fluss der Ewigkeit", "Reduziert die Abklingzeit von 'Schlag der Sieben Fäuste' um 60%"],
        ["Der Gidbinn", "Ihr beschwört manchmal einen Fetisch, wenn Ihr angreift"],
        ["Der Großwesir", "Reduziert die Arkankraftkosten von 'Meteor' um 50%"],
        ["Der Hammer des Richtspruchs", "Wenn 'Hammer der Urahnen' 3 oder weniger Ziele trifft, erhaltet Ihr 25 Wut zurück"],
        ["Der Oculus", "Chance von bis zu 20%, die Abklingzeit von 'Teleportation' zurückzusetzen, wenn Ihr Schaden erleidet"],
        ["Der Peiniger", "Ihr betört manchmal Gegner, wenn Ihr sie trefft"],
        ["Der Schmelzofen", "Erhöht den Schaden gegen Elitegegner um 50%"],
        ["Der Schwelende Kern", "Niedere Gegner werden jetzt an den Einschlagsort Eures Meteors gelockt"],
        ["Der Untergang der Dämonen", "'Stachelfalle - Klebefalle' springt auf Gegner in der Nähe über, wenn sie explodiert."],
        ["Der letzte Zeuge", "'Gleißender Schild' trifft jetzt sämtliche Gegner, die Euch umgeben"],
        ["Die Umklammerung der Spinnenkönigin", "Eure Leichenspinnen erzeugen beim Auftreffen ein Netz, das Gegner um 80% verlangsamt"],
        ["Die Verwehrung", "Jeder von Eurem 'Schwungangriff' getroffene Gegner erhöht den Schaden Eures nächsten 'Schwungangriffs' um 40%. Bis zu 5-mal stapelbar."],
        ["Die brennende Axt von Sankis", "Ihr unterdrückt manchmal Euren Schmerz, wenn Ihr getroffen werdet"],
        ["Donnerkeil", "Jeglicher Blitzschaden hat jetzt eine Chance, Gegner in Blitzableiter zu verwandeln, die Gegnern in der Nähe 6 Sekunden lang jede Sekunde 555% Waffenschaden als Blitzschaden zufügen."],
        ["Donnerzorn, Gesegnete Klinge des Windsuchers", "Chance, Eurem Gegner bei einem Treffer einen Blitzschlag zu versetzen, der 372% Waffenschaden als Blitzschaden verursacht und dann auf weitere Gegner in der Nähe überspringt. Bei jedem getroffenen Gegner werden dessen Angriffs- und Bewegungsgeschwindigkeit 3 Sek. lang um 30% reduziert. Dieser Effekt springt auf bis zu 5 zusätzliche Gegner über"],
        ["Dornen des brodelnden Hasses", "'Chakram' erzeugt 3-4 Hass"],
        ["Dunkellicht", "'Himmelsfaust' hat eine Chance von 60%, zusätzlich an Eurer Position gewirkt zu werden"],
        ["Dämonenmaschine", "Chance von 65%, explosive Pfeile zu verschießen, wenn Ihr angreift"],
        ["Eberlis Charo", "Reduziert die Abklingzeit von 'Himmelsfuror' um 50%"],
        ["Eiterspeier", "Chance von 50%, einen Säureklumpen zu werfen, wenn Ihr angreift"],
        ["Elfenbeinturm", "Geblockte Angriffe lösen ein 'Himmelsfeuer' in Blickrichtung aus"],
        ["Emimeis tiefer Beutel", "Bolas explodieren jetzt ohne Verzögerung"],
        ["Ende der Odyssee", "Feinde, die von 'Einfangender Schuss' getroffen und verlangsamt werden, erleiden um 25% erhöhten Schaden aus allen Quellen"],
        ["Erhabene Überzeugung", "Wenn Ihr einen Angriff blockt, habt Ihr basierend auf Eurer aktuellen Menge Zorn eine Chance von bis zu 20%, den Angreifer 1,5 Sek. lang zu betäuben"],
        ["Erlösung", "Wenn Ihr einen Angriff blockt, werdet Ihr und Eure Verbündeten um 30% des geblockten Betrags geheilt"],
        ["Fjordspalter", "Beim Angriff seid Ihr von einer unterkühlenden Aura umgeben."],
        ["Fliegender Drache", "Ihr verdoppelt manchmal Eure Angriffsgeschwindigkeit, wenn Ihr angreift"],
        ["Frostherz", "Gewährt eine Chance von 10%, bei einem Treffer eingefrorenen Gegnern sofort 10000% Waffenschaden als Kälteschaden zuzufügen"],
        ["Frydehrs Zorn", "'Schuldspruch' hat keine Abklingzeit mehr, aber kostet 40 Zorn"],
        ["Funkenstab der Schlange", "Ihr könnt eine zusätzliche Hydra gleichzeitig aktiv haben"],
        ["Geheiligtes Bollwerk", "'Eisenhaut' erhöht zusätzlich Euren Blockwert um 60%"],
        ["Geißel", "Chance von 45%, mit dämonischer Wut zu explodieren und 2.000% Waffenschaden als Feuerschaden zu verursachen, wenn Ihr angreift"],
        ["Genzaniku", "Ihr beschwört manchmal einen geisterhaften Champion der Gefallenen, wenn Ihr angreift"],
        ["Gerfalkenfuß", "Entfernt die Ressourcenkosten von 'Gesegneter Schild'"],
        ["Geschändetes Erbe", "Erhöht den Schaden von 'Spalten' um bis zu 400%, basierend auf dem prozentualen Anteil der aktuell verbrauchten Wut."],
        ["Goldener Häuter", "'Schwungangriff' stellt 4-6 Zorn pro getroffenem Gegner wieder her"],
        ["Hacken", "100% Eures Dornenschadens wird auf jeden Angriff angewandt"],
        ["Heiliger Ernter", "'Seelenernte' ist bis zu 10-mal stapelbar"],
        ["Held der Bastion", "'Raserei' ist bis zu 10-mal stapelbar"],
        ["Henris ewige Jagd", "Wenn ein Gegner Euch zum ersten Mal trifft, wird dieser Schaden um 80% reduziert. Darüber hinaus wird der Gegner 3 Sek. lang betört."],
        ["Himmelsschlitzer", "Ihr ruft manchmal Engelsbeistand herbei, wenn Ihr angreift"],
        ["Himmelsspalter", "Chance von 20%, 'Himmlisches Schmettern' auf getroffene Gegner zu wirken und 750% Waffenschaden als Blitzschaden zu verursachen"],
        ["Himmelswächter", "Alle 60 Sek. erhaltet Ihr 60 Sek. lang ein zufälliges Gebot"],
        ["Homunkulus", "Alle 2 Sek. wird automatisch ein Zombiehund beschworen, der an Eurer Seite kämpft"],
        ["Höllenjäger", "Chance von 10%, bei einem Treffer 'Stachelfalle', 'Krähenfüße' oder 'Geschützturm' auszulösen"],
        ["Höllenplage", "Macht Gegner manchmal bewegungsunfähig, wenn Ihr sie trefft"],
        ["Höllenschädel", "Erhöht Euren Schaden um 10%, wenn Ihr eine Zweihandwaffe verwendet"],
        ["Hühnerauge", "Chance von 50% auf ein Gegacker, wenn Ihr angreift"],
        ["Jaces Hammer der Wachsamkeit", "Vergrößert die Hämmer von 'Gesegneter Hammer'"],
        ["Jekangbrett", "'Gesegneter Schild' springt auf bis zu 4-6 weitere Gegner über"],
        ["Johannas Argument", "Erhöht die Angriffsgeschwindigkeit und den Schaden von 'Gesegneter Hammer' um 100%."],
        ["Johannas Schutzschild", "Erhöht den Schaden der ersten 3 getroffenen Gegner von 'Gesegneter Hammer' um 250%."],
        ["Justinians Gnade", "'Gesegneter Hammer' erhält den Effekt der Rune 'Herrschaft'"],
        ["Kassars Vergeltung", "Das Wirken von 'Gerechtigkeit' erhöht 2 Sek. lang Eure Bewegungsgeschwindigkeit um 20%"],
        ["Katastrophe", "Ziele, die Ihr trefft, werden todgeweiht"],
        ["Kieferbrecher", "Wenn 'Rasender Angriff' einen Gegner in mehr als 35 Metern Entfernung trifft, werden die Aufladungskosten der Fertigkeit erstattet"],
        ["Klinge der Verheißung", "Zwei Gegner, die von 'Schuldspruch' betroffen sind, rufen ebenfalls eine Explosion hervor"],
        ["Klinge des Neids", "Eure kritische Trefferchance gegen Gegner mit vollem Leben beträgt 100%"],
        ["Kriderschuss", "'Elementarpfeil' erzeugt jetzt 3-4 Hass"],
        ["Kriegsstab von General Quang", "'Gewitterfront' erhält den Effekt der Rune 'Rückenwind'"],
        ["Licht der Gnade", "'Froststrahl' durchschlägt jetzt Gegner"],
        ["Löwenbogen von Hashir", "Bolas haben eine Chance von 20%, bei ihrer Explosion alle Gegner im Umkreis von 24 Metern heranzuziehen"],
        ["Löwenklaue", "'Schlag der Sieben Fäuste' führt 7 zusätzliche Schläge aus."],
        ["Madawcs Schmerz", "Ihr betäubt Gegner für 2 Sek., wenn Ihr sie das erste Mal trefft"],
        ["Maloths Fokus", "Der Anblick dieses Stabes schlägt Gegner gelegentlich in die Flucht"],
        ["Maximus", "Chance, bei einem Treffer einen dämonischen Sklaven zu beschwören"],
        ["Maß des Zirkels", "Ihr erleidet 60% weniger Schaden von geblockten Angriffen"],
        ["Mykens Hasskugel", "'Stromschlag' kann auf Gegner überspringen, die bereits getroffen wurden"],
        ["Neunter Köcher des Cirri", "'Hungriger Pfeil' hat eine zusätzliche Chance von 25%, das Ziel zu durchschlagen"],
        ["Odyns Sohn", "Chance von 40%, einen Kettenblitz auf Eure Gegner zu wirken, wenn Ihr sie trefft"],
        ["Rabenflügel", "Ein Rabe fliegt an Eurer Seite"],
        ["Rachsüchtiger Wind", "Erhöht die maximale Stapelanzahl von 'Reißender Wind' um 7"],
        ["Rinderbardike", "Chance, bei einem Treffer eine Herde mörderischer Kühe herbeizurufen"],
        ["Rucksack des Bombenschützen", "Ihr könnt 2 zusätzliche Geschütztürme gleichzeitig aktiv haben"],
        ["Schaefers Hammer", "Ihr ladet Euch mit Blitzenergie auf, wenn Ihr eine Blitzfertigkeit einsetzt, sodass Ihr Gegnern in der Nähe 5 Sek. lang pro Sekunde 6850% Waffenschaden als Blitzschaden zufügt"],
        ["Schicksal der Grausamen", "Ihr erhaltet zwei zusätzliche Strahlen 'Himmelsfuror'"],
        ["Schlächterschnitzer", "Der Schlächter lebt in seinem Schnitzer weiter"],
        ["Schlächtersichel", "Chance von 25%, Gegner zu Euch heranzuziehen, wenn Ihr angreift"],
        ["Schnitt", "Eure Gegner platzen vor Neid"],
        ["Seelenberster", "Wenn Ihr einen Gegner tötet, explodiert er und fügt allen Gegnern im Umkreis von 20 Metern 4600% Eures Lebens pro getötetem Gegner als Schaden zu. Ihr erhaltet kein Leben pro getötetem Gegner mehr."],
        ["Shukranis Triumph", "'Geistwandler' hält an, bis Ihr angreift oder sich ein Gegner innerhalb von 30 Metern von Euch befindet"],
        ["Sloraks Wahnsinn", "Dieser Zauberstab findet Euren Tod äußerst erheiternd"],
        ["Solanium", "Kritische Treffer haben eine Chance von 3-4%, eine Heilkugel hervorzurufen"],
        ["Spiegelkugel", "'Magisches Geschoss' verschießt 2 zusätzliche Geschosse"],
        ["Splitter des Hasses", "Elementarfertigkeiten haben eine Chance, einen mächtigen Angriff auszulösen, der 250% Waffenschaden verursacht:   Kältefertigkeiten lösen 'Eisknochengeist' aus   Giftfertigkeiten lösen 'Giftnova' aus   Blitzfertigkeiten lösen 'Combo - Blitz' aus"],
        ["Stalgards Dezimierer", "Bei Nahkampfangriffen wird eine Axt auf einen Gegner in der Nähe geschleudert, die ihm 5700% Waffenschaden als physischen Schaden zufügt"],
        ["Sternstahlkukri", "Reduziert jedes Mal, wenn Eure Fetische Schaden verursachen, die Abklingzeit von 'Fetischarmee' und 'Gro ßerböser Voodoo' um 1 Sek."],
        ["Sturm der Wojahnni", "Erhöht den Schaden von 'Schnellfeuer' für jede Sekunde Kanalisieren um 40%. Dieser Effekt ist bis zu 4-mal stapelbar."],
        ["Szepter des wahnsinnigen Monarchen", "Wenn Ihr 10 Gegner getötet habt, setzt Ihr eine Giftnova frei, die Gegnern innerhalb von 30 Metern 101400% Waffenschaden als Giftschaden zufügt"],
        ["Triumvirat", "Eure Kernzauber erhöhen den Schaden von 'Arkane Kugel' 6 Sek. lang um 200%. Bis zu 3-mal stapelbar."],
        ["Tödliche Wiedergeburt", "'Umklammerung der Toten' erhält den Effekt der Rune 'Leichenregen'"],
        ["Tödliches Drama", "Verdoppelt die Anzahl der Einschläge von 'Bombardement'"],
        ["Uhkapische Schlange", "30% des Euch zugefügten Schadens wird auf Eure Zombiehunde umgelenkt"],
        ["Unerschütterlicher Glaube", "Das Wirken von 'Weihe' ruft weitere Wirkungsbereiche von 'Weihe' unter Euren Verbündeten hervor"],
        ["Unheilvolles Relikt", "Gegner, die getötet werden, während 'Akarats Champion' aktiv ist, werden 10 Sek. lang zu Avataren von 'Phalanx'"],
        ["Unnachgiebige Phalanx", "'Phalanx' wird 2-mal ausgelöst"],
        ["Vallas Vermächtnis", "Die Projektile von Speerfeuer durchschlagen Ziele."],
        ["Valtheks Zurechtweisung", "'Energiewirbel' bewegt sich jetzt geradlinig"],
        ["Vermächtnis des toten Mannes", "'Mehrfachschuss' trifft Gegner, die weniger als 60% Leben haben, zweimal"],
        ["Verteidiger der Westmark", "Einen Angriff zu blocken gewährt eine Chance, einen heranstürmenden Wolf herbeizurufen, der allen Gegnern, die er berührt, 1000% Waffenschaden zufügt"],
        ["Wachsamkeit", "Chance, 'HeiligeEinkehr' zu wirken, wenn Ihr getroffen werdet"],
        ["Walrosszahn", "Reduziert die Manakosten von 'Zombieangreifer' um 50%."],
        ["Weihrauchstab des großen Tempels", "Reduziert die Geisteskraftkosten von 'Wogedes Lichts' um 50%"],
        ["Wermut", "Belegt Gegner in der Nähe ununterbrochen mit 'Heuschreckenplage'."],
        ["Windreiter", "Verdoppelt die Dauer von 'Kavallerie'"],
        ["Wintereile", "Es besteht eine Chance von 20%, dass Gegner, die durch Kälteschaden sterben, 'Frostnova' auslösen"],
        ["Wut des vernichteten Gipfels", "Reduziert die Wutkosten von 'Seismisches Schmettern' um 50%"],
        ["Wünschelrute von Su Wong", "'Säurewolke' erhält den Effekt der Rune 'Schleimschmeißer'."],
        ["Yangs Reflexbogen", "Erhöht die Angriffsgeschwindigkeit von 'Mehrfachschuss' um 50%."],
        ["Zauberdorn", "Chance von 25%, eine gefrorene Kugel zu wirken, wenn Ihr angreift"],
        ["Zauberstab von Woh", "Nach dem Wirken von 'Explosion' werden drei weitere Explosionen ausgelöst"],
        ["Ätherwandler", "'Teleportation' hat keine Abklingzeit mehr, aber kostet 25 Arkankraft"],
    ],
    armor: [
        ["Blutrünstige Unterarmschienen", "Wenn Ihr getroffen werdet, besteht eine Chance, dass Ihr Gegnern in der Nähe 1.000% Eures Dornenschadens zufügt"],
        ["Wickeltuch des Seelenernters", "Heilkugeln stellen 30% Eurer Primärressource wieder her"],
        ["Uralte parthanische Schützer", "Für jeden betäubten Gegner im Umkreis von 25 Metern erleidet Ihr 12% weniger Schaden"],
        ["Zerbrochene Krone", "Jedes Mal, wenn ein Edelstein fallen gelassen wird, wird ebenfalls ein Edelstein des Typs fallen gelassen, der in diesen Helm gesockelt wurde."],
        ["Andariels Antlitz", "Angriffe lösen eine Giftnova aus, die allen Feinden innerhalb von 10 Metern 450% Waffenschaden als Giftschaden zufügt"],
        ["Leorics Krone", "Verstärkt die Wirkung jedes Edelsteins, der in diesen Gegenstand eingesetzt ist, um 100%."],
        ["Gungdo-Schienen", "Die durch 'Explodierende Hand' ausgelöste Explosion beim Tod fügt allen erfassten Gegnern den Effekt von 'Explodierende Hand' hinzu "],
        ["Gugel des Todessehers", "Es besteht eine Chance von 20%, dass Ihr einen untoten Gegner 2 Sek. lang betört, wenn Ihr von ihm getroffen werdet"],
        ["Fall des Hochmuts", "Wenn Ihr 5 Sek. lang keinen Schaden erleidet, werden Eure Ressourcenkosten um 30% reduziert"],
        ["Resonanzschädel", "'Drohruf' hat eine Chance, Gegner zu betören und sie auf Eure Seite überlaufen zu lassen"],
        ["Auge von Peshkov", "Reduziert die Abklingzeit von 'Odem des Himmels' um 50%"],
        ["Gyana Na Kashu", "'Fegender Tritt' entfesselt einen durchschlagenden Feuerball, der allen Gegnern im Umkreis von 10 Metern vom Aufschlagsort 700% Waffenschaden als Feuerschaden zufügt"],
        ["Kekegis unbezwingbarer Geist", "Chance, einen Effekt zu erhalten, der die Geisteskraftkosten Eurer Fertigkeiten 4 Sek. lang aufhebt, wenn Ihr einem Gegner Schaden zufügt"],
        ["Irrstein", "'Schlag der Sieben Fäuste' belegt getroffene Gegner mit 'Explodierende Hand'"],
        ["Sephs Gesetze", "Die Anwendung von 'Lichtblitz' stellt 165 Geisteskraft wieder her"],
        ["Das innere Auge", "'Heilige Einkehr' erhöht die Geisteskraftregeneration pro Sekunde um 15"],
        ["Tzo Krins Blick", "'Woge des Lichts' wird jetzt an der Position Eures Ziels ausgelöst"],
        ["Karnevalfratze", "Wenn Ihr einen Giftpfeil abschießt, verschießen Eure 5 am nächsten stehenden Fetische jedes Mal einen zusätzlichen Giftpfeil"],
        ["Jerams Maske", "Diener verursachen 100% mehr Schaden"],
        ["Quetzalcoatl", "'Heuschreckenplage' und 'Heimsuchung' verursachen ihren Schaden jetzt in der Hälfte der Zeit"],
        ["Gevatter Grins", "Wenn Ihr angreift, habt Ihr eine Chance schreckliche Abbilder zu beschwören, die einige Eurer aktiven Fertigkeiten einsetzen können."],
        ["Tiklandische Fratze", "'Entsetzen' erfüllt Gegner in Eurer Nähe 8 Sek. lang mit Furcht und macht sie bewegungsunfähig"],
        ["Fratze von Giyua", "Beschwört eine Fetischarmee, nachdem Ihr 2 Elitegegner getötet habt"],
        ["Kamelaukion des Erzmagiers", "Eure Spiegelbilder haben eine Chance, sich zu vermehren, wenn sie von Gegnern getötet werden"],
        ["Die Krone des Primus", "'Zeit verlangsamen' erhält den Effekt jeder Rune"],
        ["Schemen des dunklen Magiers", "Ihr wirkt automatisch 'Diamanthaut', wenn Ihr unter 35% Leben fallt. Dieser Effekt kann nur einmal alle 20 Sek. auftreten"],
        ["Sturmkrähe", "Chance von 40%, eine feurige Kugel zu wirken, wenn Ihr angreift"],
        ["Der Magistrat", "Eure Frosthydra wirkt jetzt in regelmäßigen Abständen 'Frostnova'"],
        ["Paulus' Kürass", "Nachdem Ihr einen Überlebensbonus erhalten habt, werdet Ihr in kurzer Zeit vollständig geheilt"],
        ["Der Swami", "Die Stärkungseffekte Eurer 'Archon'-Stapel bleiben für 20 Sek. bestehen, nachdem 'Archon' nicht mehr aktiv ist."],
        ["Samtkalotte", "Verdoppelt die Anzahl der Ziele, zu denen Euer Zauber 'Stromschlag' überspringt"],
        ["Wut der Urahnen", "'Ruf der Urahnen' erhält den Effekt der Rune 'Wut der Urahnen'."],
        ["Zielsuchplatten", "Euer Stadtportal wird nicht länger unterbrochen, wenn Ihr Schaden erleidet. Beim Wirken des Stadtportals erhaltet Ihr einen schützenden Schild, der den erlittenen Schaden um 65% reduziert."],
        ["Todeswachtmantelung", "Wenn Ihr getroffen werdet, besteht eine Chance von 35%, einen Dolchfächer auszulösen, der 950% Waffenschaden verursacht"],
        ["Schulterpanzer des Skelettkönigs", "Wenn Ihr tödlichen Schaden erleidet, besteht eine Chance, dass Ihr, statt zu sterben, auf 25% Eures maximalen Lebens geheilt werdet und Gegner in der Nähe von Furcht erfüllt fliehen"],
        ["Abscheuschutz", "Der Schaden von 'Wütender Ansturm' wird für jeden betroffenen Gegner um 35% erhöht"],
        ["Rüstung des gütigen Regenten", "'Niederstrecken' wird jetzt auch auf einen zweiten Gegner in der Nähe gewirkt"],
        ["Plattenschultern von Zakara", "Eure Gegenstände werden unzerstörbar"],
        ["Aschemantel", "Reduziert die Ressourcenkosten von Feuerfertigkeiten um 30%"],
        ["Goldhaut", "Gegner lassen manchmal Gold fallen, wenn Ihr sie trefft"],
        ["Shi Mizus Haori", "Wenn Ihr weniger als 25% Leben habt, sind alle Angriffe garantierte kritische Treffer"],
        ["Locktuch", "Wenn Ihr tödlichen Schaden erleidet, setzt Ihr, statt zu sterben, 'Rauchwolke' ein und werdet auf 25% Eures Lebens geheilt. Dieser Effekt kann einmal alle 120 Sek. auftreten"],
        ["Schwarzfeder", "Wenn Ihr einem Geschoss ausweicht oder von ihm getroffen werdet, schießt Ihr automatisch eine Zielsuchrakete auf den Angreifer, die ihm 800% Waffenschaden als physischen Schaden zufügt"],
        ["Cape des Schreckens, der die Nacht durchflattert", "Ihr lasst automatisch Krähenfüße fallen, wenn Ihr getroffen werdet. Dieser Effekt kann nur einmal alle 6 Sek. auftreten"],
        ["Der Umhang des Garwulf", "Gefährte - Wolfgefährte' beschwört jetzt 3 Wölfe"],
        ["Umhang der Täuschung", "Gegnerische Geschosse fliegen manchmal harmlos durch Euch hindurch"],
        ["Armschienen der Ersten Menschen", "Erhöht die Angriffsgeschwindigkeit von 'Hammer der Urahnen' um 50% und den Schaden um 200%."],
        ["Wickel der Obersten Spinne", "Während Ihr 'Feuerfledermäuse' kanalisiert, wird Euer erlittener Schaden um 30% reduziert und Ihr erhaltet 80000 Leben pro Treffer."],
        ["Armschienen der Zerstörung", "Erhöht den Schaden der ersten 5 getroffenen Gegner von 'Seismisches Schmettern' um 400%."],
        ["Custerische Handgelenkschützer", "Das Aufsammeln von Gold gewährt Erfahrung"],
        ["Drakons Lektion", "Wenn Euer 'Schildstoß' 3 oder weniger Gegner trifft, wird sein Schaden um 400% erhöht und 25% seiner Zornkosten werden zurückerstattet."],
        ["Jerams Armschienen", "'Todeswall' verursacht 100% mehr Schaden und kann innerhalb von 2 Sek. bis zu dreimal gewirkt werden, bevor die Abklingzeit einsetzt.'"],
        ["Gabriels Unterarmschienen", "Wenn 'GesegneterHammer' 3 oder weniger Gegner trifft, werden 100% seiner Zornkosten zurückerstattet."],
        ["Krelms Verstärkungsarmschienen", "Gewährt Immunität gegen Rückstoß und Betäubungseffekte"],
        ["Krelms Verstärkungsgürtel", "Erhöht Eure Bewegungsgeschwindigkeit um 25%. Wenn Ihr Schaden erleidet, wird dieser Effekt für 5 Sek. aufgehoben"],
        ["Armschienen der Nemesis", "Schreine und Pylonen lassen einen gegnerischen Champion erscheinen"],
        ["Verheißung", "Ihr habt eine Chance von 4-6%, dass Gegner eine Machtkugel fallen lassen, wenn Ihr sie blendet"],
        ["Ranslors Torheit", "'Energiewirbel' zieht in regelmäßigen Abständen herkömmliche Gegner innerhalb von 30 Metern heran."],
        ["Geisterschellen", "Geisteskrafterzeuger reduzieren 3 Sek. lang Euren erlittenen Schaden um 40%"],
        ["Raufboldarmschienen", "Gegner, die zurückgestoßen werden, erleiden nach dem Landen 5 Sek. lang um 30% erhöhten Schaden"],
        ["Wickel des Trag'Oul", "Heilbrunnen füllen jetzt auch sämtliche Ressourcen wieder auf und reduzieren alle Abklingzeiten um 60 Sek."],
        ["Frostbrand", "Eure Kälteeffekte haben eine Chance von bis zu 45%, Ziele einzufrieren"],
        ["Armschützer der Warzecha", "Jedes Mal, wenn Ihr ein Objekt zerstört, erhaltet Ihr einen kurzen Geschwindigkeitsschub"],
        ["Wickel der Klarheit", "Eure Hasserzeuger reduzieren Euren erlittenen Schaden 5 Sek. lang um 35%."],
        ["Gladiatorenpanzerhandschuhe", "Nachdem Ihr einen Massakerbonus erhalten habt, regnet es Gold vom Himmel"],
        ["Handschuhe der Huldigung", "Schreineffekte halten 10 Minuten an"],
        ["Tasker und Theo", "Erhöht die Angriffsgeschwindigkeit Eurer Gefährten oder Diener um 50%"],
        ["Engelshaarborte", "'Bestrafen' erhält den Effekt jeder Rune"],
        ["Gürtel des geheimen Schatzes", "Alle 8 Sek. lasst Ihr ein 'Bombardement' auf einen zufälligen Gegner in der Nähe niedergehen"],
        ["Gürtelband der Verlorenen", "Jeder Treffer mit 'Schlagder Sieben Fäuste' reduziert 7 Sek. lang Euren erlittenen Schaden um 3,5%."],
        ["Gürtel der Transzendenz", "Beschwört einen Opportunisten, wenn Ihr mit einem Eurer Manaverbraucher trefft"],
        ["Haulls Segen", "'Gerechtigkeit' erzeugt einen 'Gesegneten Hammer', wenn ein Feind damit getroffen wird"],
        ["Goldträger", "Goldsammeln: Eure Rüstung wird für 5 Sek. um einen Wert erhöht, der dem des aufgesammelten Goldes entspricht"],
        ["Band von Sherma", "Chance, bei einem Treffer ein Chaosfeld zu erzeugen, das Gegner für 3-4 Sek. blendet und verlangsamt"],
        ["Hüftgurt der Harringtons", "Wenn Ihr eine Truhe öffnet, wird Euer Schaden 10 Sek. lang um 135% erhöht"],
        ["Fazulas unmögliche Kette", "Ihr startet mit 50 'Archon'-Stapeln, wenn Ihr 'Archon' aktiviert."],
        ["Hagelsturm", "'Rachehagel' beschwört zusätzlich eine vom Himmel fallende Bestie, die 4000% Waffenschaden verursacht"],
        ["Spukgürtel", "'Heimsuchung' ruft 1 weitere Geister herbei"],
        ["Wickeltuch der Hwoj", "'Heuschreckenplage' verlangsamt Gegner um 80%"],
        ["Zorn des Jägers", "Erhöht die Angriffsgeschwindigkeit Eurer Primärfertigkeiten um 30% und ihren Schaden um 60%."],
        ["Gürtel der Unersättlichkeit", "Das Aufsammeln einer Heilkugel erhöht Euer maximales Leben 15 Sek. lang um 5%. Bis zu 5-mal stapelbar"],
        ["Vielschlitzergürtel", "'Schlitzen' wirkt in alle Richtungen"],
        ["Jangs Umhüllung", "Gegner, die durch 'Schwarzes Loch' Schaden erleiden, werden außerdem 3 Sek. lang um 80% verlangsamt"],
        ["Omryns Kette", "Beim Einsatz von 'Salto' werden 'Krähenfüße' fallen gelassen"],
        ["Heiliger Gurt", "'Richturteil' erhält den Effekt der Rune 'Entkräften' und wird an Eurem Aufschlagsort gewirkt, sobald Ihr 'Himmlische Vollstreckung' nutzt."],
        ["Messerschärpe", "Wirft mit jedem Angriff einen Dolch auf einen Gegner in der Nähe und fügt ihm 650% Waffenschaden als physischen Schaden zu"],
        ["Sebors Alptraum", "Wenn Ihr eine Kiste öffnet, wird auf alle Gegner in der Nähe 'Heimsuchung' gewirkt"],
        ["Wetzriemen", "Das Aufsammeln von Heilkugeln löst eine Explosion aus, die Gegnern im Umkreis von 20 Metern 400% Waffenschaden als Feuerschaden zufügt"],
        ["Kraft des Donnergotts", "Wenn Ihr Angriffe blockt, ihnen ausweicht oder getroffen werdet, entfesselt Ihr elektrische Blitze, die 130% Waffenschaden als Blitzschaden verursachen"],
        ["Chilaniks Kette", "Die Anwendung von 'Kriegsschrei' erhöht Eure Bewegungsgeschwindigkeit und die Eurer Verbündeten 10 Sek. lang um 40%"],
        ["Klagelied", "Gegner können mit 2 Stapeln von 'Zerfleischen' belegt werden"],
        ["Stolz von Cassius", "Erhöht die Dauer von 'Schmerzen unterdrücken' um 6 Sek."],
        ["Der unangefochtene Sieger", "'Raserei' erhält den Effekt jeder Rune"],
        ["Todeshandel", "Erhaltet eine Todesaura, die Gegnern im Umkreis von 16 Metern physischen Schaden zufügt, der 71000% Eures Lebens pro Sekunde entspricht. Ihr regeneriert kein Leben mehr."],
        ["Tiefenwühler", "Ressourcen erzeugende Primärfertigkeiten verursachen 100% zusätzlichen Schaden"],
        ["Hexenhose von Herrn Yan", "In Bewegung sind Eure Ressourcenerzeugung und Euer Schaden um 25% erhöht. Wenn Ihr stillsteht, sind sie jeweils um 25% reduziert."],
        ["Illusorische Stiefel", "Gestattet es, Euch ungehindert durch Gegner zu bewegen"],
        ["Pockenpantalons", "Wenn sich 3 oder mehr Gegner im Umkreis von 12 Metern befinden, geht von Euch ein widerlicher Gestank aus, der Gegnern im Umkreis von 15 Metern 5 Sek. lang pro Sekunde 4550% Waffenschaden als Giftschaden zufügt"],
        ["Stiefel der Missachtung", "Erhaltet für jede Sekunde, die Ihr stillsteht, zusätzlich 10.000 Lebensregeneration pro Sekunde. Dieser Effekt ist bis zu 4-mal stapelbar."],
        ["Flammengänger", "Ihr verbrennt den Boden, auf dem Ihr wandelt, und alle Gegner, die in das Feuer geraten, erleiden jede Sekunde 400% Waffenschaden"],
        ["Schlammspritzer mit Eisenkappe", "Eure Bewegungsgeschwindigkeit wird um bis zu 30% erhöht, basierend auf Eurem verlorenen Leben"],
        ["Lut-Socken", "'Sprung' kann innerhalb von 2 Sek. erneut gewirkt werden, bevor die Abklingzeit beginnt"],
        ["Nilfurs Stolz", "Erhöht den Schaden von 'Meteor' um 200%. Wenn Euer 'Meteor' 3 oder weniger Gegner trifft, erhöht sich der Schaden um 1200%."],
        ["Die gröbsten Stiefel", "'Mystischer Verbündeter' beschwört zwei mystische Verbündete, die an Eurer Seite kämpfen"],
        ["St. Archews Maß", "Der erste Treffer, den Ihr durch eine Gruppe Elitegegner erleidet, verleiht Euch 10 Sek. lang einen Schild, der Schaden in Höhe von 1150% Eures maximalen Lebens absorbiert."],
        ["Schreckenseisen", "'Aufstampfen' erzeugt einen 'Erdrutsch'"],
        ["Eiskletterer", "Ihr erhaltet Immunität gegen Einfrierungs- und Bewegungsunfähigkeitseffekte"],
    ],
    jewelry: [
        ["Kamee von Gräfin Julia", "Ignoriert sämtlichen eintreffenden Arkanschaden und heilt Euch um 25% der ignorierten Menge"],
        ["Energiefalle von Dovu", "Erhöht die Dauer von Betäubungseffekten um 25%"],
        ["Leorics goldenes Gorget", "Nach Erhalt eines Massakerbonus werden 6 Skelettwächter beschworen, die 10 Sek. lang an Eurer Seite kämpfen"],
        ["Kymbos Gold", "Wenn Ihr Gold aufsammelt, werdet Ihr um den gleichen Betrag geheilt"],
        ["Maras Kaleidoskop", "Ignoriert sämtlichen eintreffenden Giftschaden und heilt Euch um 15% der ignorierten Menge"],
        ["Mondlichtschutz", "Wenn Ihr einen Gegner im Umkreis von 15 Metern trefft, besteht die Chance, dass Ihr von Splittern arkaner Energie geschützt werdet. Diese explodieren, wenn sich Gegner nähern, und fügen Gegnern im Umkreis von 15 Metern 320% Waffenschaden als Arkanschaden zu."],
        ["Überwältigendes Verlangen", "Chance, bei einem Treffer den Gegner zu betören. Betörte Gegner erleiden 35% mehr Schaden."],
        ["Rakoffs Glas des Lebens", "Gegner, die Ihr tötet, haben eine zusätzliche Chance von 4%, eine Heilkugel fallen zu lassen"],
        ["Talisman von Aranoch", "Ignoriert sämtlichen eintreffenden Kälteschaden und heilt Euch um 15% der ignorierten Menge"],
        ["Johanns Essenz", "Chance, Gegner bei einem Treffer zu Eurem Ziel zu ziehen und sie um 80% zu verlangsamen"],
        ["Der Stern von Azkaranth", "Ignoriert sämtlichen eintreffenden Feuerschaden und heilt Euch um 15% der ignorierten Menge"],
        ["Xephirisches Amulett", "Ignoriert sämtlichen eintreffenden Blitzschaden und heilt Euch um 15% der ignorierten Menge"],
        ["Arcusstein", "Blitze springen regelmäßig zwischen allen Trägern dieses Gegenstands über und verursachen 1500% Waffenschaden"],
        ["Band der Habgier", "Jedes Mal, wenn Ihr Gold aufsammelt, wird Euer Gold- und Kugelsammelradius für 10 Sek. um 1 Meter erhöht. Bis zu mal stapelbar"],
        ["Band des leeren Raunens", "Dieser Ring sucht gelegentlich Gegner in der Nähe heim"],
        ["Band der Reuekammern", "Geisteskrafterzeuger erzeugen 50% mehr Geisteskraft"],
        ["Gebrochene Versprechen", "Nach 5 aufeinanderfolgenden Treffern ohne kritischen Treffer wird Eure Chance, einen kritischen Treffer zu landen, 3 Sek. lang auf 100% erhöht"],
        ["Bul-Kathos' Hochzeitsring", "Ihr saugt Gegnern um Euch herum das Leben aus"],
        ["Zusammenkunft der Elemente", "Erhöht den Schaden einer Schadensart 4 Sek. lang um 1200%. Der Effekt rotiert in folgender Reihenfolge zwischen den einzelnen Schadensarten, sofern sie Eurer Klasse zur Verfügung stehen: Arkan, Kälte, Feuer, Heilig, Blitz, Physisch, Gift"],
        ["Ewige Einheit", "Erhöht die Dauer der Avatare von 'Phalanx' um 200%"],
        ["Arlyses Halo", "Eure Eisrüstung reduziert nun den durch Nahkampfangriffe erlittenen Schaden um 60% und wirkt zusätzlich jedes Mal automatisch 'Frostnova', wenn Ihr mindestens 10% Eures Lebens an Schaden erlitten habt"],
        ["Vaxos Heimsuchung", "Ruft Schattenklone zu Eurer Hilfe, wenn Ihr einen Gegner betäubt. Dieser Effekt kann nur einmal alle 30 Sek. auftreten"],
        ["Höllenfeuerring", "Ihr feuert manchmal eine explosive Höllenfeuerkugel ab, wenn Ihr angreift"],
        ["Kredes Flamme", "Wenn Ihr Feuerschaden erleidet, wird Eure Primärressource wiederhergestellt"],
        ["Nagelring", "Ruft alle 12 Sek. einen Irren der Gefallenen herbei, der an Eurer Seite kämpft"],
        ["Obsidianring des Tierkreises", "Reduziert die verbleibende Abklingzeit einer Eurer Fertigkeiten um 1 Sek., wenn ein Ressourcen verbrauchender Angriff einen Gegner trifft"],
        ["Oculus-Ring", "Wenn Ihr einen Gegner tötet, besteht eine Chance, dass ein Bereich fokussierter Macht entsteht. Charaktere, die sich in diesem Bereich aufhalten, verursachen um 40% erhöhten Schaden."],
        ["Reif des Wahnsinns", "Gegner, die getötet werden, während sie von Furcht ergriffen sind, sterben in einer blutigen Explosion und lassen Gegner in der Nähe vor Furcht fliehen"],
        ["Flechtring", "Beschwört einen Schatzgoblin, der Gegenstände normaler Qualität für Euch aufsammelt. Nachdem er 16 Gegenstände aufgesammelt hat, lässt er einen seltenen Gegenstand oder möglicherweise einen legendären fallen."],
        ["Rechels Ring des Diebstahls", "Eure Bewegungsgeschwindigkeit wird 4 Sek. lang um 60% erhöht, nachdem Ihr einen Gegner mit Furcht erfüllt habt"],
        ["Ring des königlichen Prunks", "Reduziert die Anzahl der für Setboni benötigten Gegenstände um 1 (auf ein Minimum von 2)"],
        ["Rogars riesiger Stein", "Erhöht Euer Leben pro Sekunde um bis zu 100%, basierend auf Eurem verlorenen Leben"],
        ["Schädelgriff", "Erhöht den Waffenschaden von 'Wirbelwind' um 400%"],
        ["Ring des kleinen Mannes", "'Koloss' beschwört nun drei kleinere Kolosse, die alle stärker sind als der vorherige"],
        ["Ring des großen Mannes", "'Zombiehund' beschwört einen einzelnen riesigen Hund, der mehr Schaden verursacht und über mehr Leben verfügt als alle anderen Hunde zusammen"],
        ["Einheit", "Jeglicher erlittene Schaden wird zwischen den Trägern dieses Gegenstands geteilt"],
        ["Wyrdschutz", "Blitzschaden hat eine Chance von 35%, Gegner 1,5 Sek. lang zu betäuben"],
    ]
}
