"use strict";
const itemsEN = {
    weapons: [
        ["Aether Walker", "Teleport no longer has a cooldown but costs 25 Arcane Power."],
        ["Ahavarion, Spear of Lycander", "Chance on killing a demon to gain a random Shrine effect."],
        ["Akarat's Awakening", "Every successful block has a 25% chance to reduce all cooldowns by 1 second."],
        ["Akkhan's Addendum", "Akarat's Champion gains the effects of the Prophet and Embodiment of Power runes"],
        ["Akkhan's Leniency", "Each enemy hit by your Blessed Shield increases the damage of your Blessed Shield by 20% for 3 seconds"],
        ["Anessazi Edge", "Zombie Dogs stuns enemies around them for 1.5 seconds when summoned."],
        ["Arreat's Law", "Weapon Throw generates up to 20 additional Fury based on how far away the enemy hit is. Maximum benefit when the enemy hit is 20 or more yards away."],
        ["Arthef's Spark of Life", "Heal for 4% of your missing Life when you kill an Undead enemy."],
        ["Augustine's Panacea", "Elemental Arrow gains an effect based on the rune: Ball Lightning now travels at 30% speed. Frost Arrow damage and Chilled duration increased by 250%. Immolation Arrow ground damage over time increased by 250%. Lightning Bolts damage and Stun duration increased by 250%. Nether Tentacles damage and healing amount increased by 250%."],
        ["Azurewrath", "Undead and Demon enemies within 25 yards take 650% weapon damage as Holy every second and are sometimes knocked into the air."],
        ["Balance", "When your tempest rush hits 3 or fewer enemies, it gains 100% Critical Hit Chance"],
        ["Baleful Remnant", "Enemies killed while Akarat's Champion is active turn into Phalanx Avatars for 10 seconds."],
        ["Bastion's Revered", "Frenzy now stacks up to 10 times."],
        ["Blade of Prophecy", "Two Condemned enemies also trigger Condemn's explosion."],
        ["Blade of the Tribes", "War Cry and Threatening Shout cause an Avalanche and Earthquake"],
        ["Blade of the Warlord", "Bash consumes up to 40 Fury to deal up to 500% increased damage"],
        ["Blood Brother", "Grants a 20% chance to block attacks. Blocked attacks inflict 30% less damage. After blocking an attack, your next attack inflicts 30% additional damage."],
        ["Bombardier's Rucksack", "You may have 2 additional Sentries."],
        ["Bovine Bardiche", "Chance on hit to summon a herd of murderous cows."],
        ["Buriza-Do Kyanon", "Your projectiles pierce 2 additional times."],
        ["Burst of Wrath", "Killing enemies and destroying objects has a chance to grant 20% of your maximum primary resource"],
        ["Butcher's Carver", "The Butcher still inhabits his carver."],
        ["Calamity", "Enemies you hit become Marked for Death."],
        ["Cam's Rebuttal", "Falling Sword can be used again within 4 seconds before the cooldown is triggered."],
        ["Chanon Bolter", "Your Spike Traps lure enemies to them. Enemies may be taunted once every 12 seconds."],
        ["Cinder Switch", "50% chance to cast a fireball when attacking."],
        ["Cluckeye", "50% chance to cluck when attacking."],
        ["Cosmic Strand", "Teleport gains the effect of the Wormhole rune."],
        ["Coven's Criterion", "You take 60% less damage from blocked attacks."],
        ["Crystal Fist", "Dashing Strike reduces your damage taken by 50% for 6 seconds."],
        ["Danetta's Revenge", "Vault gains the effect of the Rattling Roll rune."],
        ["Danetta's Spite", "Leave a clone of yourself behind after using Vault."],
        ["Darklight", "Fist of the Heavens has a 60% chance to also be cast at your location."],
        ["Dawn", "Reduces the cooldown of Vengeance by 65%"],
        ["Dead Man's Legacy", "Multishot hits enemies below 60% health twice."],
        ["Deadly Rebirth", "Grasp of the Dead gains the effect of the Rain of Corpses rune."],
        ["Deathwish", "While channeling Arcane Torrent, Disintegrate, or Ray of Frost, all damage is increased by 35%"],
        ["Defender of Westmarch", "Blocks have a chance of summoning a charging wolf that deals 1000% weapon damage to all enemies it passes through."],
        ["Demon Machine", "65% chance to shoot explosive bolts when attacking."],
        ["Denial", "Each enemy hit by your Sweep Attack increases the damage of your next Sweep Attack by 40%, stacking up to 5 times."],
        ["Dishonored Legacy", "Cleave deals up to 400% increased damage based on percentage on missing Fury."],
        ["Eberli Charo", "Reduces the cooldown of Heaven's Fury by 50%."],
        ["Emimei's Duffel", "Bolas now explode instantly."],
        ["Envious Blade", "Gain 100% Critical Hit Chance against enemies at full health"],
        ["Etched Sigil", "Your Arcane Torrent, Disintegrate, or Ray of Frost also cast your other damaging Arcane Power Spenders every second"],
        ["Eun-jang-do", "Attacking enemies below 20% Life freezes them for 3 seconds."],
        ["Fate of the Fell", "Gain two additional rays of Heaven’s Fury."],
        ["Fjord Cutter", "You are surrounded by a Chilling Aura when attacking."],
        ["Flail of the Ascended", "Your Shield Glare deals damage equal to up to your last 5 Shield Bash casts."],
        ["Fleshrake", "Dashing Strike increases the damage of Dashing Strike by 100% for 1 second, stacking up to 5 times."],
        ["Flying Dragon", "Chance to double your attack speed when attacking."],
        ["Fortress Ballista", "Attacks grant you an absorb shield for 3% of your maximum Life, stacking up to 10 times"],
        ["Fragment of Destiny", "Spectral Blade attacks 50% faster and deals 200% increased damage."],
        ["Freeze of Deflection", "Blocking an attack has a chance to Freeze the attacker for 1.5 seconds."],
        ["Frydehr's Wrath", "Condemn has no cooldown but instead costs 40 Wrath."],
        ["Fulminator", "Lightning damage has a chance to turn enemies into lightning rods, causing them to pulse 555% weapon damage as Lightning every second to nearby enemies for 6 seconds."],
        ["Fury of the Vanished Peak", "Reduces the Fury cost of Seismic Slam by 50%."],
        ["Genzaniku", "Chance to summon a ghostly Fallen Champion when attacking."],
        ["Gesture of Orpheus", "Reduces the cooldown of Slow Time by 40%."],
        ["Golden Flense", "Sweep Attack restores 6 Wrath for each enemy hit."],
        ["Golden Scourge", "Smite now jumps to 3 additional enemies."],
        ["Guard of Johanna", "Blessed Hammer damage is increased by 250% for the first 3 enemies it hits."],
        ["Gyrfalcon's Foote", "Removes the resource cost of Blessed Shield."],
        ["Hack", "100% of your Thorns damage is applied on every attack."],
        ["Hallowed Bulwark", "Iron Skin also increases your Block Amount by 60%."],
        ["Hellrack", "Chance to root enemies to the ground when you hit them."],
        ["Hellskull", "Gain 10% increased damage while wielding a two-handed weapon."],
        ["Helltrapper", "10% chance on hit to summon a Spike Trap, Caltrops or Sentry"],
        ["Henri's Perquisition", "The first time an enemy deals damage to you, reduce that damage by 60% and Charm the enemy for 3 seconds."],
        ["Homunculus", "A Zombie Dog is automatically summoned to your side every 2 seconds."],
        ["In-geom", "Your skill cooldowns are reduced by 10 seconds for 15 seconds after killing an elite pack."],
        ["Incense Torch of the Grand Temple", "Reduces the Spirit cost of Wave of Light by 50%."],
        ["Inviolable Faith", "Casting Consecration also casts Consecration beneath all of your allies."],
        ["Ivory Tower", "Blocks release forward a Fires of Heaven."],
        ["Jace's Hammer of Vigilance", "Increase the size of your Blessed Hammers."],
        ["Jawbreaker", "When Dashing Strike hits an enemy more than 30 yards away, its Charge cost is refunded."],
        ["Jekangbord", "Blessed Shield ricochets to 6 additional enemies"],
        ["Johanna's Argument", "Increase the attack speed and damage of Blessed Hammer by 100%."],
        ["Justinian's Mercy", "Blessed Hammer gains the effect of the Dominion rune."],
        ["K'mar Tenclip", "Strafe gains the effect of the Drifting Shadow rune."],
        ["Karlei's Point", "Impale returns 20 Hatred if it hits n enemy that has already been impaled"],
        ["Kassar's Retribution", "Casting Justice increases your movement speed by 20% for 2 seconds."],
        ["Kridershot", "Elemental Arrow now generates 4 Hatred."],
        ["Kyoshiro's Blade", "When the initial impact of your Wave of Light hits 3 or fewer enemies, the damage is increased by 250%"],
        ["Last Breath", "Reduces cooldown of Mass Confusion by 20 seconds"],
        ["Leonine Bow of Hashir", "Bola Shot has a 20% chance on explosion to pull in all enemies within 24 yards."],
        ["Lianna's Wings", "Shadow Power also triggers Smoke Screen"],
        ["Light of Grace", "Ray of Frost now pierces."],
        ["Lion's Claw", "Seven-Sided Strike performs an additional 7 strikes."],
        ["Lord Greenstone's Fan", "Every second gain 200% increased damage for your next Fan of Knives"],
        ["Mad Monarch's Scepter", "After killing 10 enemies you release a Poison Nova that deals 1400% weapon damage as Poison to enemies within 30 yards."],
        ["Madawc's Sorrow", "Stun enemies for 2 seconds the first time you hit them."],
        ["Maloth's Focus", "Enemies occasionally flee at the sight of this staff."],
        ["Manticore", "Reduces the cost of Cluster Arrow by 100%"],
        ["Maximus", "Chance on hit to summon a Demonic Slave."],
        ["Mirrorball", "Magic Missile fires 2 extra missiles."],
        ["Mordullu's Promise", "Firebomb generates 125 mana"],
        ["Myken's Ball of Hate", "Electrocute can chain to enemies that have already been hit."],
        ["Oathkeeper", "Your primary skills attack 50% faster and deal 200% increased damage"],
        ["Odyn Son", "40% chance to Chain Lightning enemies when you hit them."],
        ["Odyssey's End", "Enemies snared by your Entangling Shot take 25% increased damage from all sources."],
        ["Orb of Infinite Depth", "Each time you hit an enemy with Explosive Blast your damage is increased by 5% and your damage reduction is increased by 15% for 6 seconds. This effect can stack up to 4 times."],
        ["Piro Marella", "Reduces the Wrath cost of Shield Bash by 50%."],
        ["Primordial Soul", "Elemental Exposure's damage bonus per stack is creased to 10%"],
        ["Pus Spitter", "50% chance to lob an acid blob when attacking."],
        ["Remorseless", "Hammer of the Ancients has a 30% chance to summon an Ancient for 20 seconds."],
        ["Rhen'ho Flayer", "Plague of Toads now seek out enemies and can explode twice."],
        ["Rimeheart", "10% chance on hit to instantly deal 10000% weapon damage as Cold to enemies that are Frozen."],
        ["Sacred Harvester", "Soul Harvest now stacks up to 10 times."],
        ["Salvation", "Blocked attacks heal you and your allies for 30% of the amount blocked"],
        ["Schaefer's Hammer", "Casting a Lightning skill charges you with Lightning, causing you to deal 850% weapon damage as Lightning every second for 5 seconds to nearby enemies."],
        ["Scourge", "45% chance when attacking to explode with demonic fury for 2000% weapon damage as Fire."],
        ["Scrimshaw", "Reduces the Mana cost of Zombie Charger by 50%."],
        ["Serpent's Sparker", "You may have one extra Hydra active at a time."],
        ["Sever", "Slain enemies rest in pieces."],
        ["Shard of Hate", "Elemental skills have a chance to trigger a powerful attack that deals 250% weapon damage:Cold skills trigger Freezing Skull, Poison skills trigger Poison Nova Lightning skills trigger Charged Bolt"],
        ["Shield of Fury", "Each time an enemy takes damage from your Heaven's Fury, it increases the damage they take from your Heaven's Fury by 20%"],
        ["Shukrani's Triumph", "Spirit Walk lasts until you attack or until an enemy is within 30 yards of you."],
        ["Sin Seekers", "Rapid Fire no longer has a channel cost"],
        ["Sky Splitter", "20% chance to Smite enemies for 750% weapon damage as Lightning when you hit them."],
        ["Skycutter", "Chance to summon angelic assistance when attacking."],
        ["Skywarden", "Every 60 seconds, gain a random Law for 60 seconds."],
        ["Slorak's Madness", "This wand finds your death humorous."],
        ["Solanium", "Critical Hits have a 4% chance to spawn a health globe."],
        ["Soulsmasher", "When you kill an enemy, it explodes for 600% of your Life per Kill as damage to all enemies within 20 yards. You no longer benefit from your Life per Kill"],
        ["Spines of Seething Hatred", "Chakram now generates 4 Hatred."],
        ["Staff of Chiroptera", "Firebats attack 100% faster and cost 75% less Mana"],
        ["Stalgard's Decimator", "Your melee attacks throw a piercing axe at a nearby enemy, dealing 700% weapon damage as Physical."],
        ["Standoff", "Furious Charge gains increased damage equal to 250% of your bonus movement speed"],
        ["Starmetal Kukri", "Reduce the cooldown of Fetish Army and Big Bad Voodoo by 1 second each time your fetishes deal damage."],
        ["SuWong Diviner", "Acid Cloud gains the effect of the Lob Blob Bomb rune."],
        ["Sublime Conviction", "When you block, you have up to a 20% chance to Stun the attacker for 1.5 seconds based on your current Wrath."],
        ["Sunder", "50% chance to sunder the ground your enemies walk on when you attack."],
        ["Swiftmount", "Doubles the duration of Steed Charge."],
        ["Sword of Ill Will", "Chakram deals 1.4% increased damage for each point of Hatred you have"],
        ["The Burning Axe of Sankis", "Chance to fight through the pain when enemies hit you."],
        ["The Butcher's Sickle", "25% chance to drag enemies to you when attacking."],
        ["The Dagger of Darts", "Your Poison Darts and your Fetishes' Poison Darts now pierce."],
        ["The Demon's Demise", "Spike Trap - Sticky Trap spreads to nearby enemies when it explodes."],
        ["The Final Witness", "Shield Glare now hits all enemies around you."],
        ["The Fist of Az'Turrasq", "Exploding Palm's on-death explosion damage is increased by 300%."],
        ["The Flow of Eternity", "Increase the damage of Seven-Sided Strike by 100% and reduces the cooldown of Seven-Sided Strike by 60%."],
        ["The Furnace", "Increases damage against elites by 50%."],
        ["The Gavel of Judgment", "Hammer of the Ancients returns 25 Fury if it hits 3 or less enemies."],
        ["The Gidbinn", "Chance to summon a Fetish when attacking."],
        ["The Grand Vizier", "Reduces the Arcane Power cost of Meteor by 50%."],
        ["The Mortal Drama", "Double the number of Bombardment impacts."],
        ["The Ninth Cirri Satchel", "Hungering Arrow has 25% additional chance to pierce."],
        ["The Oculus", "Taking damage has up to a 20% chance to reset the cooldown on Teleport."],
        ["The Raven's Wing", "A raven flies to your side."],
        ["The Smoldering Core", "Lesser enemies are now lured to your Meteor impact areas."],
        ["The Spider Queen's Grasp", "Corpse Spiders releases a web on impact that Slows enemies by 80%."],
        ["The Three Hundredth Spear", "Increase the damage of Weapon Throw and Ancient Spear by 60%"],
        ["The Tormentor", "Chance to charm enemies when you hit them."],
        ["The Twisted Sword", "Energy Twister damage is increased by 150% for each Energy Twister you have out up to a maximum of 8."],
        ["Thing of the Deep", "Increases Gold and Health Pickup by 20 yards"],
        ["Thunderfury, Blessed Blade of the Windseeker", "Chance on hit to blast your enemy with Lightning, dealing 372% weapon damage as Lightning and then jumping to additional nearby enemies. Each enemy hit has their attack speed and movement speed reduced by 30% for 3 seconds. Jumps up to 5 targets."],
        ["Triumvirate", "Your Signature Spells increase the damage of Arcane Orb by 200% for 6 seconds, stacking up to 3 times."],
        ["Uhkapian Serpent", "30% of the damage you take is redirected to your Zombie Dogs."],
        ["Unrelenting Phalanx", "Phalanx now casts twice."],
        ["Unstable Scepter", "Arcane Orb's explosion triggers an additional time"],
        ["Valla's Bequest", "Strafe projectiles pierce."],
        ["Valthek's Rebuke", "Energy Twister now travels in a straight path."],
        ["Vengeful Wind", "Increases the maximum stack count of Sweeping Wind by 7"],
        ["Vigilance", "Getting hit has a chance to automatically cast Inner Sanctuary."],
        ["Vile Hive", "Locust Swarm gains the effect of the Pestillence rune and deals 60% increased damage"],
        ["Vo'Toyias Spiker", "Enemies affected by Provoke take double damage from Thorns."],
        ["Voo's Juicer", "Spirit Barrage gains the effects of the Phlebotomize and The Spirit is Willing runes"],
        ["Wall of Man", "30% chance to be protected by a shield of bones when you are hit."],
        ["Wand of Woh", "3 additional Explosive Blasts are triggered after casting Explosive Blast."],
        ["Warstaff of General Quang", "Tempest Rush gains the effect of the Tailwind rune."],
        ["Wilken's Reach", "Grasp of the Dead no longer has a cooldown"],
        ["Winter Flurry", "Enemies killed by Cold damage have a 20% chance to release a Frost Nova."],
        ["Wizardspike", "Performing an attack has a 25% chance to hurl a Frozen Orb."],
        ["Wojahnni Assaulter", "Rapid Fire deals 75% more damage for every second that you channel. Stacks up to 4 times."],
        ["Wormwood", "Locust Swarm continuously plagues enemies around you."],
        ["Yang's Recurve", "Multishot attacks 40% faster."],
    ],
    armor: [
        ["Akkhan's Manacles", "Blessed Shield damage is increased by 500% for the first enemy it hits"],
        ["Ancient Parthan Defenders", "Each stunned enemy within 25 yards reduces your damage taken by 12%."],
        ["Andariel's Visage", "Attacks release a Poison Nova that deals 450% weapon damage as Poison to enemies within 10 yards."],
        ["Angel Hair Braid", "Punish gains the effect of every rune."],
        ["Aquila Curiass", "While above 90% primary resource, all damage taken is reduced by 50%"],
        ["Archmage's Vicalyke", "Your Mirror Images have a chance to multiply when killed by enemies."],
        ["Armor of the Kind Regent", "Smite will now also be cast at a second nearby enemy."],
        ["Ashnagarr's Blood Bracers", "Increase the potency of your shields by 100%"],
        ["Bakuli Jungle Wraps", "Firebats deals 200% increased damage to enemies affected by Locust Swarm or Piranhas."],
        ["Beckon Sail", "When receiving fatal damage, you instead automatically cast Smoke Screen and are healed to 25% Life. This effect may occur once every 120 seconds."],
        ["Belt of Transcendence", "Summon a Fetish Sycophant when you hit with a Mana spender."],
        ["Belt of the Trove", "Every 8 seconds, call down Bombardment on a random nearby enemy."],
        ["Binding of the Lost", "Each hit with Seven-Sided Strike grants 3.5% damage reduction for 7 seconds."],
        ["Bindings of the Lesser Gods", "Enemies hit by your cyclone strike take 200% more damage from your Mystic Ally for 5 seconds"],
        ["Blackfeather", "Dodging or getting hit by a ranged attack automatically shoots a homing rocket back at the attacker for 800% weapon damage as Physical."],
        ["Blessed of Haull", "Justice spawns a Blessed Hammer when it hits an enemy."],
        ["Boots of Disregard", "Gain 10000 Life Regeneration per second for each second you stand still. This effect stacks up to 8 times"],
        ["Bracers of Destruction", "Seismic Slam deals 400% increased damage to the first two enemies it hits."],
        ["Bracers of Fury", "Heaven's Fury deals 200% increased damage to enemies that are Blinded, Immobilized, or Stunned"],
        ["Bracers of the First Men", "Hammer of the Ancients attacks 50% faster and deals 200% increased damage."],
        ["Broken Crown", "Whenever a gem drops, a gem of the type socketed into this item also drops."],
        ["Cape of the Dark Night", "Automatically drop Caltrops when you are hit. This effect may only occur once every 6 seconds."],
        ["Carnevil", "Your Fetishes shoot a Poison Dart every time you do."],
        ["Cesar's Memento", "Enemies take 400% increased damage from your Tempest Rush for 5 seconds after you hit them with a Blind, Freeze, or Stun"],
        ["Chain of Shadows", "After using Impale, your Vaunt costs no resources for 2 seconds"],
        ["Chaingmail", "After earning a survival bonus, quickly heal to full Life."],
        ["Chilanik's Chain", "Using War Cry increases the movement speed for you and all allies affected by 40% for 10 seconds."],
        ["Cindercoat", "Reduces the resource cost of Fire skills by 30%."],
        ["Cloak of Deception", "Enemy missiles sometimes pass through you harmlessly."],
        ["Coils of the First Spider", "While channeling Firebats, you take 30% reduced damage and gain 80,000 Life per hit."],
        ["Cord of the Sherma", "Chance on hit to create a chaos field that Blinds and Slows enemies inside for 4 seconds."],
        ["Crashing Rain", "Rain of Vengeance also summons a crashing beast that deals 4000% weapon damage."],
        ["Crown of the Primus", "Slow Time gains the effect of every rune."],
        ["Custerian Wristguards", "Picking up gold grants experience."],
        ["Dark Mage's Shade", "Automatically cast Diamond Skin when you fall below 35% Life. This effect may occur once every 15 seconds."],
        ["Death Watch Mantle", "35% chance to explode in a fan of knives for 950% weapon damage when hit."],
        ["Death's Bargain", "Gain an aura of death that deals 1000% of your Life per Second to enemies within 20 yards. You no longer regenerate Life"],
        ["Deathseer's Cowl", "20% chance on being hit by an Undead enemy to charm it for 2 seconds."],
        ["Depth Diggers", "Primary skills that generate resource deal 100% additional damage."],
        ["Drakon's Lesson", "When your Shield Bash hits 3 or less enemies, its damage is increased by 400% and 25% of its Wrath Cost is refunded."],
        ["Dread Iron", "Ground Stomp causes an Avalanche."],
        ["Eye of Peshkov", "Reduce the cooldown of Breath of Heaven by 50%."],
        ["Fazula's Improbable Chain", "You automatically start with 50 Archon stacks when entering Archon form."],
        ["Fire Walkers", "Burn the ground you walk on, dealing 400% weapon damage each second."],
        ["Frostburn", "Cold skills deal 20% increased damage and have a 50% chance to Freeze enemies."],
        ["Fury of the Ancients", "Call of the Ancients gains the effect of the Ancients' Fury rune."],
        ["Gabriel's Vambraces", "When your Blessed Hammer hits 3 or fewer enemies, 100% of its Wrath Cost is refunded."],
        ["Gladiator Gauntlets", "After earning a massacre bonus, gold rains from sky."],
        ["Gloves of Worship", "Shrine effects last for 10 minutes."],
        ["Goldskin", "Chance for enemies to drop gold when you hit them."],
        ["Goldwrap", "On gold pickup: Gain armor for 5 seconds equal to the amount picked up."],
        ["Gungdo Gear", "Exploding Palm's on-death explosion applies Exploding Palm."],
        ["Gyana Na Kashu", "Lashing Tail Kick releases a piercing fireball that deals 700% weapon damage as Fire to enemies within 10 yards on impact."],
        ["Hammer Jammers", "Enemies take 400% increased damage from your Blessed Hammers for 10 seconds after you hit them with a Blind, Immobilize, or Stun"],
        ["Harrington Waistguard", "Opening a chest grants 135% increased damage for 10 seconds."],
        ["Haunting Girdle", "Haunt releases 1 extra spirit."],
        ["Heart of Iron", "Gain Thorns equal to 300% of your Vitality"],
        ["Hergbrash's Bindings", "Reduces the Arcane Power cost of Arcane Torrent, Disintegrate, and Ray of Frost by 65%"],
        ["Hexing Pants of Mr. Yan", "Your resource generation and damage is increased by 25% while moving and decreased by 20% while standing still."],
        ["Homing Pads", "Your Town Portal is no longer interrupted by taking damage. While casting Town Portal you gain a protective bubble that reduces damage taken by 65%."],
        ["Hunter's Wrath", "Your Hatred generators attack 30% faster and deal 40% increased damage."],
        ["Hwoj Wrap", "Locust Swarm also Slows enemies by 80%."],
        ["Ice Climbers", "Gain immunity to Freeze and Immobilize effects."],
        ["Illusory Boots", "You may move unhindered through enemies."],
        ["Insatiable Belt", "Picking up a Health Globe increases your maximum Life by 5% for 15 seconds, stacking up to 5 times"],
        ["Irontoe Mudsputters", "Gain up to 30% increased movement speed based on amount of Life missing."],
        ["Jang's Envelopment", "Enemies damaged by Black Hole are also slowed by 80% for 3 seconds."],
        ["Jeram's Bracers", "Wall of Death can be cast up to twice again within 2 seconds before the cooldown begins."],
        ["Kekegi's Unbreakable Spirit", "Damaging enemies has a chance to grant you an effect that removes the Spirit cost of your abilities for 4 seconds."],
        ["Krelm's Buff Belt", "Gain 25% run speed. This effect is lost for 5 seconds after taking damage."],
        ["Krelm's Buff Bracers", "You are immune to Knockback and Stun effects."],
        ["Kyoshiro's Soul", "Sweeping Wind gains 2 stacks every second it does not deal damage to any enemies"],
        ["Lakumbra's Ornament", "Reduces all damage taken by 6% for each stack of Soul Harvest you have"],
        ["Lamentation", "Rend can now stack up to 2 times on an enemy."],
        ["Lefebvre's Soliloquy", "Cyclone Strike reduces your damage taken by 50% for 5 seconds"],
        ["Leorics Crown", "Increase the effect of any gem socketed into this item by 100%."],
        ["Lut Socks", "Leap can be cast again within 2 seconds before the cooldown begins."],
        ["Madstone", "Your Seven-Sided Strike applies Exploding Palm."],
        ["Magefist", "Fire skills deal 20% increased damage."],
        ["Mantle of Channeling", "While channeling Whirlwind, Rapid Fire, Strafe, Tempest Rush, Firebats, Arcane Torrent, Disintegrate, or Ray of Frost, you deal 25% increased damage and take 25% reduced damage"],
        ["Mask of Jeram", "Pets deal 100% more damage."],
        ["Nemesis Bracers", "Shrines and Pylons will spawn an enemy champion."],
        ["Nilfur's Boast", "Increase the damage of Meteor by 200%. When your Meteor hits 3 or less enemies, the damage is increased by 350%."],
        ["Omnislash", "Slash attacks in all directions."],
        ["Omryn's Chain", "Drop Caltrops when using Vault."],
        ["Pauldrons of the Skeleton King", "When receiving fatal damage, there is a chance that you are instead restored to 25% of maximum Life and cause nearby enemies to flee in fear."],
        ["Pinto's Pride", "Wave of Light also Slows enemies by 80% for 3 seconds and deals 150% increased damage"],
        ["Pox Faulds", "When 3 or more enemies are within 12 yards, you release a vile stench that deals 550%weapon damage as Poison every second for 5 seconds to enemies within 15 yards."],
        ["Pride of Cassius", "Increases the duration of Ignore Pain by 6 seconds."],
        ["Pride's Fall", "Your resource costs are reduced by 30% after not taking damage for 5 seconds"],
        ["Promise of Glory", "6% chance to spawn a Nephalem Glory globe when you Blind an enemy."],
        ["Quetzalcoatl", "Locust Swarm and Haunt now deal their damage in half of the normal duration."],
        ["Ranslor's Folly", "Energy Twister periodically pulls in lesser enemies within 30 yards."],
        ["Razor Strop", "Picking up a Health Globe releases an explosion that deals 400% weapon damage as Fire to enemies within 20 yards."],
        ["Reaper's Wraps", "Health globes restore 30% of your primary resource."],
        ["Rivera Dancers", "Lashing Tail Kick attacks 50% faster and deals 300% increased damage"],
        ["Sacred Harness", "Judgment is cast at your landing location when casting Falling Sword."],
        ["Sanguinary Vambracers", "Chance on being hit to deal 1000% of your Thorns damage to nearby enemies."],
        ["Sash of Knives", "With every attack, you throw a dagger at a nearby enemy for 650% weapon damage as Physical."],
        ["Sebor's Nightmare", "Haunt is cast on all nearby enemies when you open a chest."],
        ["Shi Mizu's Haori", "While below 25% Life, all attacks are guaranteed Critical Hits."],
        ["Skular's Salvation", "When your Boulder Toss hits 5 or fewer enemies the damage is increased by 150%"],
        ["Skull of Resonance", "Threatening Shout has a chance to Charm enemies and cause them to join your side."],
        ["Spaulders of Zakara", "Your items become indestructible."],
        ["Spirit Guards", "Your Spirit Generators reduce your damage taken by 40% for 3 seconds."],
        ["St. Archew's Gage", "The first time an elite pack damages you, gain an absorb shield equal to 150% of your maximum Life for 10 seconds."],
        ["Storm Crow", "40% chance to cast a fiery ball when attacking."],
        ["String of Ears", "Reduces damage from melee attacks by 30%"],
        ["Strongarm Bracers", "Enemies hit by knockbacks suffer 30% more damage for 5 seconds when they land."],
        ["Swamp Land Waders", "Sacrifice deals 400% additional damage against enemies affected by Locust Swarm or Grasp of the Dead."],
        ["Tasker and Theo", "Increase attack speed of your pets by 50%."],
        ["The Cloak of the Garwulf", "Companion - Wolf Companion now summons 3 wolves."],
        ["The Crudest Boots", "Mystic Ally summons two Mystic Allies that fight by your side."],
        ["The Grin Reaper", "Chance to summon horrific Mimics when attacking."],
        ["The Laws of Seph", "Using Blinding Flash restores 165 Spirit."],
        ["The Magistrate", "Frost Hydra now periodically casts Frost Nova."],
        ["The Mind's Eye", "Inner Sanctuary increases Spirit Regeneration per second by 15."],
        ["The Shame of Delsere", "Your Signature Spells attack 50% faster and restore 12 Arcane Power"],
        ["The Swami", "The bonuses from Archon stacks now last for 20 seconds after Archon expires."],
        ["The Undisputed Champion", "Frenzy gains the effect of every rune."],
        ["Thundergod's Vigor", "Blocking, dodging or being hit causes you to discharge bolts of electricity that deal 130% weapon damage as Lightning."],
        ["Tiklandian Visage", "Horrify causes you to Fear and Root enemies around you for 8 seconds."],
        ["Trag'Oul Coils", "Healing wells replenish all resources and reduce all cooldowns by 60 seconds."],
        ["Tzo Krin's Gaze", "Wave of Light is now cast at your enemy."],
        ["Vambracers of Sescheron", "Primary skills heal you for 6% of your missing life"],
        ["Velvet Camaral", "Double the number of enemies your Electrocute jumps to."],
        ["Vile Ward", "Furious Charge deals 35% increased damage for every enemy hit while charging."],
        ["Visage of Giyua", "Summon a Fetish Army after you kill 2 Elites."],
        ["Visage of Gunes", "Vengeance gains the effect of the Dark Heart rune"],
        ["Warhelm of Kassar", "Reduce the cooldown and increase the damage of Phalanx by 60%"],
        ["Warzechian Armguards", "Every time you destroy a wreckable object, you gain a short burst of speed."],
        ["Wraps of Clarity", "Your Hatred Generators reduce your damage taken by 35% for 5 seconds."],
        ["Zoey's Secret", "You take 9% less damage for each Companion you have active"],
    ],
    jewelry: [
        ["Arcstone", "Lightning pulses periodically between all wearers of this item, dealing 1500% weapon damage."],
        ["Avarice Band", "Each time you pick up gold, increase your Gold and Health Pickup radius by 1 yard for 10 seconds, stacking up to 30 times"],
        ["Band of Hollow Whispers", "This ring occasionally haunts nearby enemies."],
        ["Band of Might", "After using Furious Charge, Ground Stomp, or Leap, gain 60% damage reduction for 8 seconds."],
        ["Band of the Rue Chambers", "Your Spirit Generators generate 50% more Spirit."],
        ["Broken Promises", "After 5 consecutive non-critical hits, your chance to critically hit is increased to 100% for 3seconds."],
        ["Bul'Kathos's Wedding Band", "You drain life from enemies around you."],
        ["Convention of Elements", "Gain 200% increased damage to a single element for 4 seconds. This effect rotates through the elements available to your class in the following order: Arcane, Cold, Fire, Holy, Lightning, Physical, Poison."],
        ["Countess Julia's Cameo", "Prevent all Arcane damage taken and heal yourself for 25% of the amount prevented."],
        ["Dovu Energy Trap", "Increases duration of Stun effects by 25%."],
        ["Elusive Ring", "After using Vault, Shadow Power, or Smoke Screen, take 60% reduced damage for 8 seconds"],
        ["Eternal Union", "Increases the duration of Phalanx avatars by 200%."],
        ["Golden Gorget of Leoric", "After earning a massacre bonus, 6 Skeletons are summoned to fight by your side for 10 seconds"],
        ["Halo of Arlyse", "Your Ice Armor now reduces damage from melee attacks by 60% and automatically casts Frost Nova whenever you take 10% of your Life in damage."],
        ["Halo of Karini", "You take 60% less damage for 3 seconds after your Storm Armor electrocutes an enemy more than 30 yards away."],
        ["Haunt of Vaxo", "Summons shadow clones to your aid when you Stun an enemy. This effect may occur once every 30 seconds."],
        ["Hellfire Ring", "Chance on hit to engulf the ground in lava, dealing 200% weapon damage per second for 6 seconds."],
        ["Justice Lantern", "Gain damage reduction equal to 55% of your Block chance."],
        ["Krede's Flame", "Taking Fire damage restores your primary resource."],
        ["Kymbo's Gold", "Picking up gold heals you for an amount equal to the gold that was picked up."],
        ["Mara's Kaleidoscope", "Prevent all Poison damage taken and heal yourself for 15% of the amount prevented."],
        ["Moonlight Ward", "Hitting an enemy within 15 yards has a chance to ward you with shards of Arcane energy that explode when enemies get close, dealing 320% weapon damage as Arcane to enemies within 15 yards."],
        ["Nagelring", "Summons a Fallen Lunatic to your side every 10 seconds."],
        ["Obsidian Ring of the Zodiac", "Reduce the remaining cooldown of one of your skills by 1 seconds when you hit with a resource-spending attack."],
        ["Oculus Ring", "Chance to create an area of focused power on killing a monster. Damage is increased by 85% while standing in the area."],
        ["Overwhelming Desire", "Chance on hit to charm the enemy. While charmed, the enemy takes 35% more damage"],
        ["Pandemonium Loop", "Enemies slain while Feared die in a bloody explosion for 800% weapon damage and cause other nearby enemies to flee in Fear"],
        ["Puzzle Ring", "Summon a treasure goblin who picks up normal-quality items for you. After picking up 12 items, he drops a rare item with a chance for a legendary."],
        ["Rakoff's Glass of Life", "Enemies you kill have a 4% additional chance to drop a health globe."],
        ["Rechel's Ring of Larceny", "Gain 60% increased movement speed for 4 seconds after Fearing an enemy."],
        ["Ring of Emptiness", "You deal 100% increased damage to enemies affected by both your Haunt and Locust Swarm"],
        ["Ring of Royal Grandeur", "Reduces the number of items needed for set bonuses by 1 (to a minimum of 2)."],
        ["Rogar's Huge Stone", "Increase your Life per Second by up to 100% based on your missing Life."],
        ["Skull Grasp", "Increase the damage of Whirlwind by 300% weapon damage."],
        ["Talisman of Aranoch", "Prevent all Cold damage taken and heal yourself for 15% of the amount prevented."],
        ["The Ess of Johan", "Chance on hit to pull in enemies toward your target and Slow them by 80%."],
        ["The Short Man's Finger", "Gargantuan instead summons three smaller gargantuans each more powerful than before."],
        ["The Star of Azkaranth", "Prevent all Fire damage taken and heal yourself for 15% of the amount prevented."],
        ["The Tall Man's Finger", "Zombie Dogs instead summons a single gargantuan dog with more damage and health than all other dogs combined."],
        ["Unity", "All damage taken is split between wearers of this item."],
        ["Wyrdward", "Lightning damage has a 35% chance to Stun for 1.5 seconds."],
        ["Xephirian Amulet", "Prevent all Lightning damage taken and heal yourself for 15% of the amount prevented."],
    ]
};
